apiVersion: v1
kind: Service
metadata:
  labels:
    project: bookstack
    role: app
  name: bookstack
  namespace: pope
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 6875
  selector:
    project: bookstack
    role: app
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: bookstack
    role: app
    version: staging
  name: bookstack
  namespace: pope
spec:
  replicas: 3
  selector:
    matchLabels:
      project: bookstack
      role: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: bookstack
        role: app
      name: bookstack
    spec:
      containers:
        - args:
            - ./entrypoint.sh
          image: >-
            gcr.io/rd-devops/bookstack
          imagePullPolicy: Always
          name: bookstack
          ports:
            - containerPort: 6875
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 6875
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: '0.2'
              memory: 512Mi
            requests:
              cpu: '0.01'
              memory: 256Mi
          stdin: true
          volumeMounts:
            - mountPath: /ENVS
              name: variables
      volumes:
        - name: variables
          secret:
            secretName: bookstack-secret